# parameter.yml

site_title: My Keratine Application

database:
    options:
        # unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock # MAMP unix socket
        driver: pdo_mysql
        host: localhost
        dbname:
        user:
        password:
        charset: utf8
        driverOptions:
            1002: SET NAMES utf8

translator:
    ressources:
        fr: %root_dir%/locales/fr.yml