# parameter.yml

site_title: My Keratine Application

session:
    name: _sample

database:
    options:
        driver: pdo_mysql
        host: localhost
        dbname: _your_dbname_
        user: _your_user_
        password: _your_password_
        charset: utf8
        driverOptions:
            1002: SET NAMES utf8

translator:
    ressources:
        fr: %root_dir%/locales/fr.yml

zendsearch:
    indices_path: []